### ISSUE TITLE
Run Prettier linter

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/tutorial#2]
## Goal:

Speed up reviewing PRs by enforcing one code style for the project.

## Todo:

- [ ] Install Prettier linter as development dependency
- [ ] Create basic Prettier config
- [ ] Create two `script` entries in the `package.json` file:
  - [ ] `prettier` that runs Prettier with the `--cache` option
  - [ ] `prettier-fix` that runs prettier with the `--cache` option _and_ fixes the files
- [ ] Create basic GitHub Action run to check if the `prettier` command run passes

**Comment by PhilipAbed** [comment]
adding extra dependencies to this project might change the outcome of the results of the tutorial right? :D

**Comment by HonkingGoose** [comment]
I'm probably getting something mixed up here. 🙈😄 

The goal for this project is: [^comment]

> I would like for us to have a specific "demo" repository with a hands-on getting started guide where users can fork it and follow the guide to experience Renovate. E.g. starting simply with onboarding but then showing:
> 
> - making config changes during onboarding and seeing the change
> - making changes after, e.g. adding package rules and common features like labels, assignees, etc.
> 
> This should be part of our "official" documentation and maintained to stay accurate.

When we say "maintained to stay accurate" do we mean:

- update the project dependencies ourselves/with Renovate?
- update the documentation whenever Renovate bot configuration or other upstream like Kubernetes/AWS/Docker changes?
- both of the above?

Do we _want_ this repository to have "stale dependencies"? So that the examples in the doc match the behavior after people fork the `renovatebot/tutorial` repository?

Right now, I don't understand _why_ adding Prettier may cause problems. 😉 

[^comment]: https://github.com/renovatebot/renovate/issues/15384#issuecomment-1113906255

**Comment by PhilipAbed** [comment]
ill test it out, thing is, we have Screenshots of the dependencies, 
im hoping renovate `config:base` ignores devDependencies if it changes the Order of the dependencies, i will give it a test
